name: Java CI with Maven

# Trigger only on main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_DIR: app

jobs:
  build:
    runs-on: self-hosted      # Change to "ubuntu-latest" if NOT using self-hosted runners

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show branch info
        run: |
          echo "Current branch = ${{ github.ref_name }}"

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('app/pom.xml') }}
          restore-keys: |
            m2-${{ runner.os }}-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven Build (skip tests)
        working-directory: ${{ env.APP_DIR }}
        run: mvn -B clean package -DskipTests

      - name: Show built artifacts
        run: |
          echo "Contents of app/target:"
          ls -la app/target || true
